export const data = [
  {
    _id: "628a9949488855a1a7167080",
    name: "Onion",
    image:
      "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/BONI11.png",
    weight: "1 kg",
    prize: 16,
    old_prize: 19,
    category: " Vegetables",
    sub_category: " Onion, Potato & Tomatoes",
    description: "Onion",
    benifit:
      "- Onions are low in fat and calories, but rich in soluble dietary fibers. - The chemicals in onions are good for helping with swelling, lowering cholesterol and blood sugars. - Onions are rich in antioxidants which helps in lowering the risk of several types of cancer. - The fibre in onion helps in improving the gut health & managing the blood pressure. - Onion Nutritions also include Vitamin B6, C & other compounds which help in improving skin & hair.",
    info: "- Onions are usually stored in a dry place. - Ever wondered why cutting onions makes you cry, well it is because of the lachrymatory compound in onions which causes irritation to the eyes. - To avoid the irritation to eyes while cutting onions, one can simply chill the onions in the refrigerator for 30 mins or run the half-cut onions under the water and then chop them. - You can try some Quick Onion Recipes like Onion Rings, Pyaaz ke Pakode/ Kanda Bhajji or some Traditional Indian Recipes like Paneer Do Pyaaza or Pyaaz Kachori are also very famous.",
    tag: "best",
    createdAt: "2022-05-22T20:12:57.703Z",
    updatedAt: "2022-05-22T20:12:57.703Z",
  },
  {
    _id: "628a99db488855a1a7167082",
    name: "Special Offer Watermelon",
    image:
      "https://s3.ap-south-1.amazonaws.com/fraazo-prod/images/images/000/004/598/original/data?1647718256",
    weight: "1 pc",
    prize: 9,
    old_prize: 26,
    category: " Fruits",
    sub_category: " Oranges, Mosambi & Melons",
    description: "Special Offer Watermelon",
    benifit: "No Details Available",
    info: "No Details Available",
    tag: "best",
    createdAt: "2022-05-22T20:15:23.160Z",
    updatedAt: "2022-05-22T20:15:23.160Z",
  },
  {
    _id: "628a9a22488855a1a7167084",
    name: "Rich Candy Cherry",
    image:
      "https://s3.ap-south-1.amazonaws.com/fraazo-prod/images/images/000/007/492/original/data?1652237337",
    weight: "200g",
    prize: 99,
    old_prize: null,
    category: " Fruits",
    sub_category: " Exotic Fruits",
    description: "Rich Candy Cherry",
    benifit:
      "- Cherries are high in antioxidants and provide a variety of health benefits, including vitamin C, potassium, fiber and other elements required for proper bodily function. - Cherries helps to improve athletic performance and reduce exercise-induced muscle damage and soreness. - It contains powerful heart-protective properties.",
    info: "- Natural Fresh Cherry comes from a Himachal Pradesh farm. These cherries have a longer shelf life, lasting up to 6 days from 2-3 days. - Sweet, sour, and duke cherries are among the many sorts of cherry available. - The fresh cherry crop was harvested in the first week of May and will continue until the end of June. - Cherry are popular from Himachal Pradesh, in northern India, as a viable alternative to apple trees.",
    tag: "best",
    createdAt: "2022-05-22T20:16:34.724Z",
    updatedAt: "2022-05-22T20:16:34.724Z",
  },
  {
    _id: "628a9a63488855a1a7167086",
    name: "Musk Melon/ Kharabooja",
    image:
      "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/FMUS1.png",
    weight: "1 pc",
    prize: 28,
    old_prize: 35,
    category: " Fruits",
    sub_category: " Oranges, Mosambi & Melons",
    description: "Musk Melon/ Kharabooja",
    benifit:
      "Musk melons are cooling and help in constipation, bladder infections, ulcers, fatigue, colitis, and blood pressure.",
    info: 'Musk melons (Kharbuja) sabzi quick simple and easy to make. Muskmelons, also known as sweet melon, kharbuja, and cantaloupe, are a member of the Cucurbitaceae family and therefore are botanically known as Cucumis melo. A strong "muskmelon" pleasant aroma is produced by a ripe melon.',
    tag: "best",
    createdAt: "2022-05-22T20:17:39.914Z",
    updatedAt: "2022-05-22T20:17:39.914Z",
  },
  {
    _id: "628a9a97488855a1a7167088",
    name: "Watermelon",
    image:
      "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/117/original/data?1616765390",
    weight: "1 pc",
    prize: 19,
    old_prize: 26,
    category: " Fruits",
    sub_category: " Oranges, Mosambi & Melons",
    description: "Watermelon",
    benifit:
      "Watermelon Health Benefits - Watermelon has a high water content, so it helps us in being hydrated. - Helps in weight loss, as it keeps us full - Watermelon has a good amount of electrolyte which helps to reduce the risk of heatstroke and is good for kidney Watermelon Nutrition - Fat-free & Low in sodium - Has a good amount of water content - Good source of lycopene, amino acids & antioxidants - Source of vitamin A, B6, C & potassium.",
    info: "- Watermelon can be stored in the refrigerator for about 2 weeks. - It should be covered with plastic wrap or can be cut & refrigerated. - The red pulp of watermelons can be consumed in the form of juice, eaten as it is or as an accompaniment in fruit salads. - Must try Watermelon Recipes include Watermelon Cooler, Watermelon juice, Watermelon jelly, Watermelon popsicle & more. Did you know? - Watermelon is actually a fruit & a vegetable. - It is also considered to be the biggest berry.",
    tag: "best",
    createdAt: "2022-05-22T20:18:31.779Z",
    updatedAt: "2022-05-22T20:18:31.779Z",
  },
  {
    _id: "628a9ad5488855a1a716708a",
    name: "Bottle Gourd (Dudhi / Lauki)",
    image:
      "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/117/original/data?1616765390",
    weight: "1 pc",
    prize: 13,
    old_prize: 22,
    category: " Vegetables",
    sub_category: " Daily Veggies",
    description: "Bottle Gourd (Dudhi / Lauki)",
    benifit:
      "Bottle Gourd Nutrition - Has zero fat & cholesterol content - Good source of Vitamin C & minerals like potassium, calcium & sodium - Rich in fibre Bottle Gourd Health Benefits - Helps in weight loss - Treats UTI - Cools our body, so usually preferred after a workout - Keeps our heart healthy & relieves stress",
    info: "Bottle gourds can be sauted, fried, grilled, or converted into pickles. It can also be prepared as curry or used to make delicacies. Some famous Indian dishes with bottle gourd are Sorakkai Poriyal, Lauki kofta, Lauki thepla, Lauki Sabzi, Lauki Halwa, Lauki Paratha, & more. Did you know? - Bottle gourd belongs to the pumpkin family.",
    tag: "best",
    createdAt: "2022-05-22T20:19:33.929Z",
    updatedAt: "2022-05-22T20:19:33.929Z",
  },
  {
    _id: "628a9b31488855a1a716708c",
    name: "Brinjal Bharta",
    image:
      "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/VBRI12.png",
    weight: "500 g",
    prize: 21,
    old_prize: 23,
    category: " Vegetables",
    sub_category: " Daily Veggies",
    description: "Brinjal Bharta",
    benifit: "No Details Available",
    info: "No Details Available",
    tag: "best",
    createdAt: "2022-05-22T20:21:05.604Z",
    updatedAt: "2022-05-22T20:21:05.604Z",
  },
  {
    _id: "628a9b5a488855a1a716708e",
    name: "Pumpkin Green",
    image:
      "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/101/original/data?1612451098",
    weight: "500 g",
    prize: 12,
    old_prize: null,
    category: " Vegetables",
    sub_category: " Daily Veggies",
    description: "Pumpkin Green",
    benifit: "No Details Available",
    info: "No Details Available",
    tag: "",
    createdAt: "2022-05-22T20:21:46.428Z",
    updatedAt: "2022-05-22T20:21:46.428Z",
  },
  {
    _id: "628a9b9a488855a1a7167090",
    name: "Capsicum (Shimla), Green Shimla Mirchi",
    image:
      "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/101/original/data?1612451098",
    weight: "250 g",
    prize: 18,
    old_prize: null,
    category: " Vegetables",
    sub_category: " Daily Veggies",
    description: "Capsicum (Shimla), Green Shimla Mirchi",
    benifit:
      "- Capsicum helps you burn fat and lose weight. The capsicum veggie also improves digestion. - Capsicum lowers the risk of cancer as it contains anti-inflammatory nutrients and antioxidants. - Capsicum includes a chemical called capsaicin, which is thought to prevent pain from reaching the spinal cord. It is beneficial in the treatment of herpes zoster and neuralgia pain. It helps to alleviate discomfort.",
    info: "- Capsicum has a low fat level, as well as a high fiber and water content.",
    tag: "best",
    createdAt: "2022-05-22T20:22:50.212Z",
    updatedAt: "2022-05-22T20:22:50.212Z",
  },
  {
    _id: "628a9bef488855a1a7167092",
    name: "Cucumber Green Indian / Kheera / Kakdi",
    image:
      "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/315/original/data?1614700255",
    weight: "500 g",
    prize: 21,
    old_prize: null,
    category: " Vegetables",
    sub_category: " Daily Veggies",
    description: "Cucumber Green Indian / Kheera / Kakdi",
    benifit:
      "- Cucumbers are low in calories and high in water and soluble fiber, making it a great choice for encouraging hydration and fat loss. खीरा में विटामिन सी, बीटा कैरोटीन जैसे एंटी ऑक्सीडेंट्स पाए जाते हैं. जिससे शरीर में मौजूद फ्री रेडिकल्स दूर होते हैं - Cucumber peel reversed most of the diabetes-associated changes and caused a decrease in blood sugar. - Cucumber is known for its anti-cancer properties and reduces risk of cancer spread in your body.",
    info: "- Cucumbers can be used as essential to bring freshness and taste to salads, sandwiches, and side dishes, as well as to replace more calorie options. - Cucumbers are high in water and promote hydration. - Cucumbers can be eaten fresh or pickled. They can be enjoyed as a low-calorie snack or used to add flavor in a variety of dishes.",
    tag: "",
    createdAt: "2022-05-22T20:24:15.368Z",
    updatedAt: "2022-05-22T20:24:15.368Z",
  },
  {
    _id: "628a9c71488855a1a7167094",
    name: "Cabbage",
    image:
      "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/VCAB12.png",
    weight: "1 pc ",
    prize: 20,
    old_prize: null,
    category: " Vegetables",
    sub_category: " Daily Veggies",
    description: "Cabbage",
    benifit:
      "- Green cabbage is high in dietary fibre, as well as vitamins C, K, and B-complex vitamins. - It's also high in potassium, folate, calcium, iron, magnesium, and phosphorus, as well as the minerals calcium, iron, magnesium, and phosphorus. - Green cabbage, like other cruciferous vegetables, is high in polyphenols and sulphur compounds, which have antibacterial and antioxidant properties. - Green Cabbage helps to improve digestion providing fuel for friendly bacteria and promoting regular bowel movements. - It also helps to reduce the risk of heart disease.",
    info: "- Green cabbage offers a sweet, grassy flavor with a mustardy finish. - Cabbage is a leafy green, crimson (purple), or white (pale green) biennial plant used for its dense-leaved heads as an annual vegetable crop. It is a descendant of wild cabbage.",
    tag: "best",
    createdAt: "2022-05-22T20:26:25.810Z",
    updatedAt: "2022-05-22T20:26:25.810Z",
  },
  {
    _id: "628a9c9e488855a1a7167096",
    name: " Cauliflower",
    image:
      "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/VCAB12.png",
    weight: "1 pc ",
    prize: 38,
    old_prize: null,
    category: " Vegetables",
    sub_category: " Daily Veggies",
    description: " Cauliflower",
    benifit: "No Details Available",
    info: "No Details Available",
    tag: "",
    createdAt: "2022-05-22T20:27:10.785Z",
    updatedAt: "2022-05-22T20:27:10.785Z",
  },
  {
    _id: "628a9cc7488855a1a7167098",
    name: "Bitter Gourd (Karela)",
    image:
      "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/VBIT12.png",
    weight: "500 g",
    prize: 25,
    old_prize: null,
    category: " Vegetables ",
    sub_category: " Daily Veggies ",
    description: "Bitter Gourd (Karela)",
    benifit: "No Details Available",
    info: "No Details Available",
    tag: "",
    createdAt: "2022-05-22T20:27:51.819Z",
    updatedAt: "2022-05-22T20:27:51.819Z",
  },
  {
    _id: "628a9d53488855a1a716709a",
    name: "Pumpkin Red",
    image:
      "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/VPUM12.png",
    weight: "500 g",
    prize: 25,
    old_prize: null,
    category: " Vegetables ",
    sub_category: " Daily Veggies ",
    description: "Pumpkin Red",
    benifit: "No Details Available",
    info: "No Details Available",
    tag: "",
    createdAt: "2022-05-22T20:30:11.985Z",
    updatedAt: "2022-05-22T20:30:11.985Z",
  },
  {
    _id: "628a9d82488855a1a716709c",
    name: "Brinjal Kateri, Baingan",
    image:
      "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/VPUM12.png",
    weight: "500 g",
    prize: 14,
    old_prize: 20,
    category: " Vegetables ",
    sub_category: " Daily Veggies ",
    description: "Brinjal Kateri, Baingan",
    benifit:
      "- Kateri Brinjals are rich in fiber and polyphenols, making them a good choice for controlling blood sugar and for diabetics.",
    info: "- Brinjals are cousins of potatoes, tomatoes, and bell peppers and belong to the Family Solanaceae, also known as nightshades. - Brinjals of this kind are small and oval in shape, and are often consumed in Indian households. - This type of brinjal is small and oval in shape, and it is commonly consumed in Indian households; commonly used to make Indian curries.",
    tag: "best",
    createdAt: "2022-05-22T20:30:58.720Z",
    updatedAt: "2022-05-22T20:30:58.720Z",
  },
  {
    _id: "628a9daa488855a1a716709e",
    name: " Drumstick",
    image:
      "https://fraazo-master.s3.ap-south-1.amazonaws.com/products/VDRU12.png",
    weight: "100 g",
    prize: 8,
    old_prize: null,
    category: " Vegetables ",
    sub_category: " Daily Veggies ",
    description: " Drumstick",
    benifit: "No Details Available",
    info: "No Details Available",
    tag: "",
    createdAt: "2022-05-22T20:31:38.436Z",
    updatedAt: "2022-05-22T20:31:38.436Z",
  },
  {
    _id: "628a9e00488855a1a71670a0",
    name: "Snake Gourd (Bada Parwal)",
    image:
      "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/106/original/data?1603884029",
    weight: "250 g",
    prize: 20,
    old_prize: null,
    category: " Vegetables ",
    sub_category: " Daily Veggies ",
    description: "Snake Gourd (Bada Parwal)",
    benifit: "No Details Available",
    info: "No Details Available",
    tag: "",
    createdAt: "2022-05-22T20:33:04.809Z",
    updatedAt: "2022-05-22T20:33:04.809Z",
  },
  {
    _id: "628a9e31488855a1a71670a2",
    name: " Cucumber White",
    image:
      "https://s3.ap-south-1.amazonaws.com/fraazo-prod/products/product_images/000/000/316/original/data?1614700848",
    weight: "500 g",
    prize: 19,
    old_prize: null,
    category: " Vegetables ",
    sub_category: " Daily Veggies ",
    description: " Cucumber White",
    benifit:
      "Cucumbers have a minimal calorie, carbohydrate, salt, fat, and cholesterol content due to their natural composition. Not only are white cucumbers high in water, but they also include key nutrients like magnesium and potassium that aid in hydration. Cucumbers white contain anti-inflammatory compounds that help in the removal of waste and reduce skin damage and irritation.",
    info: "Cucumber is a very healthy and versatile vegetable. Cucumber White Wonder can thrive outside of a greenhouse on a sunny and sheltered plot. Cucumber works well with lettuce, sweet pepper, cheese, apple, carrot, mint, chives, potatoes, radishes, onion, rice, pasta and almonds to name a few.",
    tag: "",
    createdAt: "2022-05-22T20:33:53.888Z",
    updatedAt: "2022-05-22T20:33:53.888Z",
  },
];
